# This version of config.mak was generated by:
# ./configure --includedir=/home/abc/nhat/optee_examples/eevm_minimal_ta/build_oe_libs/musl/include CFLAGS=-DSYSCALL_NO_INLINE CC=aarch64-none-linux-gnu-gcc CXX='aarch64-none-linux-gnu-g++'
# Any changes made here will be lost if configure is re-run
ARCH = aarch64
SUBARCH = 
ASMSUBARCH = 
srcdir = .
prefix = /usr/local/musl
exec_prefix = $(prefix)
bindir = $(exec_prefix)/bin
libdir = $(prefix)/lib
includedir = /home/abc/nhat/optee_examples/eevm_minimal_ta/build_oe_libs/musl/include
syslibdir = /lib
CC = aarch64-none-linux-gnu-gcc
CFLAGS = -DSYSCALL_NO_INLINE
CFLAGS_AUTO = -Os -pipe -fomit-frame-pointer -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -fdata-sections -Werror=implicit-function-declaration -Werror=implicit-int -Werror=pointer-sign -Werror=pointer-arith
CFLAGS_C99FSE = -std=c99 -nostdinc -ffreestanding -fexcess-precision=standard -frounding-math -Wa,--noexecstack
CFLAGS_MEMOPS = -fno-tree-loop-distribute-patterns
CFLAGS_NOSSP = -fno-stack-protector
CPPFLAGS = 
LDFLAGS = 
LDFLAGS_AUTO = -Wl,--sort-section,alignment -Wl,--sort-common -Wl,--gc-sections -Wl,--hash-style=both -Wl,--no-undefined -Wl,--exclude-libs=ALL -Wl,--dynamic-list=./dynamic.list
CROSS_COMPILE = 
LIBCC = -lgcc -lgcc_eh
OPTIMIZE_GLOBS = internal/*.c malloc/*.c string/*.c
ALL_TOOLS =  obj/musl-gcc
TOOL_LIBS =  lib/musl-gcc.specs
ADD_CFI = no
WRAPCC_GCC = $(CC)
